image: docker:latest
variables:
  DOCKER_DRIVER: overlay2
  RELEASE_IMAGE: registry.gitlab.com/islandoftex/images/context
services:
  - docker:dind
stages:
  - build

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - docker info

build:beta:
  stage: build
  script:
    - IMAGETAG="context-beta-`date +%Y-%m-%d-%H-%M`-$CI_COMMIT_SHORT_SHA"
    - docker build -f Dockerfile.mkivbeta --tag $RELEASE_IMAGE:$IMAGETAG --tag $RELEASE_IMAGE:beta .
    - docker push $RELEASE_IMAGE:$IMAGETAG
    - docker push $RELEASE_IMAGE:beta

build:current:
  stage: build
  script:
    - IMAGETAG="context-current-`date +%Y-%m-%d-%H-%M`-$CI_COMMIT_SHORT_SHA"
    - docker build -f Dockerfile.mkivcurrent --tag $RELEASE_IMAGE:$IMAGETAG --tag $RELEASE_IMAGE:current .
    - docker push $RELEASE_IMAGE:$IMAGETAG
    - docker push $RELEASE_IMAGE:current

build:lmtx:
  stage: build
  script:
    - IMAGETAG="context-lmtx-`date +%Y-%m-%d-%H-%M`-$CI_COMMIT_SHORT_SHA"
    - docker build -f Dockerfile.lmtx --tag $RELEASE_IMAGE:$IMAGETAG --tag $RELEASE_IMAGE:lmtx .
    - docker push $RELEASE_IMAGE:$IMAGETAG
    - docker push $RELEASE_IMAGE:lmtx
